### ISSUE TITLE
How to create menu bar button on left with beside pagemenu in swift 3

### ISSUE THREAD

**Issue by diliptiwari333** [subinspathilettu/SJSegmentedViewController#108]
https://i.stack.imgur.com/A3ApK.png I want to create this UI using this lib i m having two tabs at top which slide also they were working fine but i need to create create menu bar button on left with beside pagemenu

**Comment by subinspathilettu** [comment]
@diliptiwari333 You can't create/add menu button in SegmentedBar. Current implementation is not supported for this.
