### ISSUE TITLE
Observer register Issue

### ISSUE THREAD

**Issue by kishanraiyani03** [subinspathilettu/SJSegmentedViewController#12]
Hello,
I have just integrated your library.
When I alloc first time, it works proper. Then I change root view controller of window for logout.
Then I again login and change root view controller to the SJSegmentedViewController.
It says
"An instance 0x7fa0e38b5600 of class UICollectionView was deallocated while key value observers were still registered with it."

I have collection view in my class So I have implemeted as per your doc to observer the scrolling
extension HomeVC: SJSegmentedViewControllerViewSource {
    
    func viewForSegmentControllerToObserveContentOffsetChange(controller: UIViewController,
                                                              index: Int) -> UIView {
        return self.clcView
    }

Let me know the solution because I am in hurry.
Thanks.

**Comment by subinspathilettu** [comment]
@kishanraiyani03 ,

We have pushed a new version (1.1.0) of SJSegmentedScrollView to [CocoaPods](https://cocoapods.org/pods/SJSegmentedScrollView). Please verify.

**Comment by kishanraiyani03** [comment]
It works.
Thanks.
