### ISSUE TITLE
Cannot build with version 1.2.1 without changing to lower version

### ISSUE THREAD

**Issue by takaishota** [subinspathilettu/SJSegmentedViewController#16]
HI,

Thank you for your useful library.

I've used your library from old version, and upgraded my product to support swift 3.0.
But I can't build with version 1.2.1, because deployment target become iOS10.0.
My product support iOS9.3 and over, so I have changed iOS Deployment Target in project setting of Pods from iOS10.0 to iOS9.3.

Can you change deployment target to iOS9.3? Is there a problem?

Thanks.

**Comment by sarrathy** [comment]
Same issue here . Kindly change it as soon as possible . it would be a great help

**Comment by subinspathilettu** [comment]
Hi, 
I have updated deployment target to 9.0 in the latest version, 1.2.2. Could you please check and let me know.

**Comment by takaishota** [comment]
Hi,
Thank you for quick response.
I've been able to build with version 1.2.2.

Thanks!

**Comment by subinspathilettu** [comment]
Okay, then I am going to close this issue.
