### ISSUE TITLE
Does it support iOS8?

### ISSUE THREAD

**Issue by fishfisher** [subinspathilettu/SJSegmentedViewController#18]
It says in the requirements: iOS 8.0+, Swift 2.3+.
However, the minimum platform has to be '9.0' to install via CocoaPods.
Does it not support iOS 8?

**Comment by subinspathilettu** [comment]
We upgraded the latest version to Swift 3 and minimum platform to 9. If you want to support older version, please use 

> pod ’SJSegmentedScrollView’, ‘1.1.0'

The minimum platform version for version 1.1.0 is 8.

**Comment by fishfisher** [comment]
Aa, I see. Is there a reason you are dropping iOS 8 support?
My app is iOS8 and up and I am using Swift 3.
Would love to use your implementation.

**Comment by subinspathilettu** [comment]
@fishfisher  We are planning to keep support from iOS 9 only as maintenance for platform below can create a trauma in future. Thank you.
