### ISSUE TITLE
sidemen crash with different segmentControllers count

### ISSUE THREAD

**Issue by Mgap** [subinspathilettu/SJSegmentedViewController#20]
hi @subinspathilettu 
 I get crash , after i going to 2 segment layout , and  going to view with 3 segmented menu the app will crash , out of index , aim using in swift 2.2 , any solution?

**Comment by subinspathilettu** [comment]
Could you please provide some more details or your code?

**Comment by Mgap** [comment]
hi @subin
thanks for the response 
i get crash in here 
   func didChangeSegmentIndex(notification: NSNotification) 
out of index in sjsegmentView

but i motif the fund like this 
   func didChangeSegmentIndex(notification: NSNotification) {
        
        //deselect previous buttons
        for button in segments {
            button.selected = false
        }

        // select current button
        let index = notification.object as? Int
                print(index)
    
        if index! != 2 {
        let button = segments[index!]
                  button.selected = true
        }else {
            segments.append(UIButton())
        let button = segments[index!]
                  button.selected = true
        }

    }

is working fine now

**Comment by subinspathilettu** [comment]
Okay. So I am closing this issue. 

Thanks
