### ISSUE TITLE
Strange scrolling behaviour when dragging from tableviews

### ISSUE THREAD

**Issue by nemwiper** [subinspathilettu/SJSegmentedViewController#21]
Hi everybody,
I see a strange behaviour when you scroll up.
To replicate this problem you have, in the example app, to:
- Scroll down a bit, but not enough to pin the segmented view to the top  
- Scroll up again, tapping on the tableview, NOT on the header NOR on the segmented view

If you scroll with the "inertia" you can observe that the scrollingview doesn't acquire the normal "velocity", but it stops instantaneously.
This effect makes the navigation in the section a little weird, you can sense that something is wrong, but it's difficult to figure it out what!!

**Comment by subinspathilettu** [comment]
Hi @nemwiper,

We are not able to reproduce this scenario. Could you please provide a video for this scenario?

**Comment by nemwiper** [comment]
Hi @subinspathilettu, thanks for the quick response!!!

This is a video of the issue, as you can see, when scrolling up dragging from the tableview (when it reaches the top element), the movement of the scrollview stops as you release the mouse, instead of continue to move upward.

![a](https://cloud.githubusercontent.com/assets/14993175/19762026/8aa0293a-9c38-11e6-8802-054013d0b6b7.gif)

**Comment by subinspathilettu** [comment]
Ohh.. got it.. Thanks @nemwiper 

After reaches the top element, we are using UIScrollView scroll changes to update the view. The deceleration rate for UITableView and UIScrollView is different. So that it suddenly stops after releasing the touch/mouse. I will look into this issue and provide an update.

**Comment by nemwiper** [comment]
@subinspathilettu, thankyou very much! ;)

**Comment by nemwiper** [comment]
Hi @subinspathilettu,
another small issue: 
when one drags up starting from the table view it's all fine, but when the dragging starts from the header or from the segment view, the scroll view stops scrolling once the fragment view reaches the top, and the "movement" will not propagate to the tableview! ;)
With this two issues resolved I think that this library will be perfect! :)

![a](https://cloud.githubusercontent.com/assets/14993175/19974059/7f821ed2-a1e7-11e6-8c69-ad70354ef5ab.gif)

**Comment by nemwiper** [comment]
Why this issue has been closed? It's still present in the last version! :(

**Comment by wongzigii** [comment]
Any update on this issue?
