### ISSUE TITLE
How i set the image on the segmented tab bar instead of title?

### ISSUE THREAD

**Issue by HariNarayanan777** [subinspathilettu/SJSegmentedViewController#22]
I try to set image on tab bar, but it won't come

Its come like this
![simulator screen shot 16 nov 2016 13 28 25](https://cloud.githubusercontent.com/assets/10630354/20339191/f610f4a6-ac00-11e6-93ba-f302a402e9dc.png)

I tried this code in the below function
firstViewController.tabBarItem.image = UIImage(named: "1-1.png")

> func getSJSegmentedViewController() -> SJSegmentedViewController? {
>         
>         if let storyboard = self.storyboard {
>             
>             let headerViewController = storyboard
>                 .instantiateViewController(withIdentifier: "HeaderViewController1")
>             
>             let firstViewController = storyboard
>                 .instantiateViewController(withIdentifier: "FirstTableViewController")
>             //firstViewController.title = "Table View"
>             **firstViewController.tabBarItem.image = UIImage(named: "1-1.png")**

**Comment by subinspathilettu** [comment]
@HariNarayanan777 Currently we didn't add image support for segment tab. We will add this feature in next release and let you know.

**Comment by subinspathilettu** [comment]
@HariNarayanan777 ,

You can customize the segment tab view by providing controller.navigationItem.titleView.

// Custom ImageView
let view = UIImageView()
view.frame.size.width = 100
view.image = UIImage(named: imageName)
view.contentMode = .scaleAspectFit
view.backgroundColor = .white

firstViewController.navigationItem.titleView = view

**Comment by HariNarayanan777** [comment]
@subinspathilettu super its working.......
