### ISSUE TITLE
can i create this segment view as dynamic ??/

### ISSUE THREAD

**Issue by HariNarayanan777** [subinspathilettu/SJSegmentedViewController#24]
i need to create the swipeable segment view like you but that viewcontroller and its title should be come as fully dynamically ??? can i do that?
Please tell is it possible in this or if you can!!!!

**Comment by subinspathilettu** [comment]
@HariNarayanan777 Do you want to change the title in runtime?

**Comment by HariNarayanan777** [comment]
yes i am trying lord form array list @subinspathilettu

**Comment by subinspathilettu** [comment]
@HariNarayanan777 Can you be more specific? I am not able to identify your requirement/ problem. You can provide title by `ViewController.title` or you can provide a custom view for the segment by `ViewController.navigationItem.titleView`.
