### ISSUE TITLE
API to select the segment to display

### ISSUE THREAD

**Issue by yodasl** [subinspathilettu/SJSegmentedViewController#26]
Great project! So thanks for open sourcing it.
Quick question: I looked at the API but I can't seem to find a way for selecting the segment I would like to display. 
Imagine the case where depending on the action the user did in a previous ViewController, when the SJSegmentViewController is shown, I need to show the 2nd or 3rd segment when it appears on screen. Right now the default behavior is always to show the first segment, but I would like to be able to specify something like:
self.segmentedViewController.selectedSegmentIndex = 2

and when it goes on screen, it is automatically showing the proper segment.
thanks

**Comment by subinspathilettu** [comment]
@yodasl, we have added a function, `func setSelectedSegmentAt(_ index: Int, animated: Bool)` to select a segment in latest version` 1.3.3`.

`segmentControl.setSelectedSegmentAt(index, animated: true)`

Could you please use the latest version and check?

**Comment by yodasl** [comment]
Thanks... I was still on 1.2.2 and upgrading to 1.3.3 I see now the new API... You may want to consider updating the README so when adding the reference for the pod for SJSegmentedScrollView to use 1.3.3
