### ISSUE TITLE
Funny height Issues

### ISSUE THREAD

**Issue by hassanmah** [subinspathilettu/SJSegmentedViewController#27]
Hey 

I have set up the view controller as per the instructions, but I am getting some funny issues with the height. 

This is my view from the debugging state. As you can see the SJSegmentedView doesn't extend to the navigation bar or to the tab bar.

<img width="516" alt="screen shot 2016-11-30 at 16 41 40" src="https://cloud.githubusercontent.com/assets/3025707/20762198/838ae9dc-b71d-11e6-8255-ab210df5426d.png">

**Comment by subinspathilettu** [comment]
Hi @hassanmah,

Could you please check in the latest version, `1.3.3`? We have resolved this issue in the latest version.

**Comment by hassanmah** [comment]
Hi 

I am using the latest version

**Comment by SonnetXavier** [comment]
Could you please be more precise on how you have used the [SJSegmentedView](https://github.com/subinspathilettu/SJSegmentedViewController), like Presented, Pushed or Added as a Child View Controller?

**Comment by hassanmah** [comment]
@subinspathilettu I am using it like so:

```
import UIKit

class InspirationViewController: SJSegmentedViewController {

    override func viewDidLoad() {
        
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        
        let recipeViewController = storyboard
            .instantiateViewController(withIdentifier: "RecipeViewController")
        recipeViewController.title = "Recipe"
        let fitnessViewController = storyboard
            .instantiateViewController(withIdentifier: "FitnessViewController")
        fitnessViewController.title = "Fitness"
        
        let insightViewController = storyboard
            .instantiateViewController(withIdentifier: "InsightsViewController")
        insightViewController.title = "Insights"
        
        segmentControllers = [recipeViewController, fitnessViewController, insightViewController]
        
        segmentTitleColor = UIColor.white
        segmentBackgroundColor = UIColor(rgba: "#2EB8B8")
        headerViewHeight = 0
        segmentViewHeight = 50.0
        selectedSegmentViewHeight = 3.0
        segmentTitleColor = UIColor(rgba: "#1F7D7D")
//        segmentShadow = SJShadow.light()
        segmentedScrollView.segmentView?.frame.size.height = self.view.frame.size.height
        super.viewDidLoad()

        // Do any additional setup after loading the view.
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
}
```
Am I using it incorrectly?

**Comment by SonnetXavier** [comment]
Hi @hassanmah , Please let us know the purpose of following line,

`segmentedScrollView.segmentView?.frame.size.height = self.view.frame.size.height`

Hope you are using as static library and we recommend to use as pod,

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target '<Your Target Name>' do
pod ’SJSegmentedScrollView’, ‘1.3.3'
end
```

**Comment by hassanmah** [comment]
Hi @SonnetXavier , please ignore this line, it was in error

`segmentedScrollView.segmentView?.frame.size.height = self.view.frame.size.height
`

I am now using it as pod and still getting the same behaviour

**Comment by SonnetXavier** [comment]
Hi @hassanmah , We just tried out and were not able to reproduce the error. We have some queries, please answer these so that we could help you to figure out the exact issue.
1. Is the `InspirationViewController` Presented or Pushed?
2. To which type of View/View Controller  is `InspirationViewController` being presented ?

Meanwhile, you can try out adding `segmentedViewController` as Child view controller. Code snippet follows: 


```
class InspirationViewController: UIViewController {

    override func viewDidLoad() {
      
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        
        let recipeViewController = storyboard
            .instantiateViewController(withIdentifier: "RecipeViewController")
        recipeViewController.title = "Recipe"
        let fitnessViewController = storyboard
            .instantiateViewController(withIdentifier: "FitnessViewController")
        fitnessViewController.title = "Fitness"
        
        let insightViewController = storyboard
            .instantiateViewController(withIdentifier: "InsightViewController")
        insightViewController.title = "Insights"
        
        let segmentedViewController = SJSegmentedViewController(headerViewController: nil,
                                                                segmentControllers: [recipeViewController, fitnessViewController, insightViewController]
addChildViewController(segmentedViewController)
        self.view.addSubview(segmentedViewController.view)
        segmentedViewController.view.frame = self.view.bounds
        segmentedViewController.didMove(toParentViewController: self)
          super.viewDidLoad()
    }

```

**Comment by hassanmah** [comment]
Hi @SonnetXavier , to your questions `InspirationViewController` is a rootviewcontroller of a navigation controller and the first view controller of a tab controller. The flow is as follows

`[tab controller] >> [navigation controller] >> [InspirationViewController]`

Adding `segmentedViewController` as Child view controller gives me the following screenshot:

![screen shot 2016-12-02 at 11 57 40](https://cloud.githubusercontent.com/assets/3025707/20833232/8f9680dc-b886-11e6-8f0e-bc3e5c978e92.png)

**Comment by SonnetXavier** [comment]
Hi @hassanmah, 
Our team will be working on this issue. 
Attached is a sample project without the height issues, You could follow this and give it a try!
[TestHeightIssue.zip](https://github.com/subinspathilettu/SJSegmentedViewController/files/630284/TestHeightIssue.zip)

**Comment by hassanmah** [comment]
@SonnetXavier still having problems. In reference to "Adding segmentedViewController as Child view controller" screenshot the space at the bottom is 50px, the exact height of the tab bar. 

Could this issue be created by the tab bar?

**Comment by SonnetXavier** [comment]
We are not able to recreate the issue. If possible, please share your project with us.
