### ISSUE TITLE
it crashes index segments tab error in swift 2.3

### ISSUE THREAD

**Issue by chojunyng** [subinspathilettu/SJSegmentedViewController#28]
I use this framework at tabor controller
It works well, but one thing is disable and crash app
when i use tabbar controller which has controllers three and five view controller each other(second view, third view)
first, tab third view and click segment third button and return my second view
and I touched five or four segment button suddenly crashed index error
I found it at SJSegmentedViewController initial problem at nsnotification
but, i can't fix it from now on...
thank you for this framework in use, I will hope this error fixed well soon ....
how can i fix it?

**Comment by SonnetXavier** [comment]
Hi @chojunyng ,
Thank you for using [SJSegmentedView](https://github.com/subinspathilettu/SJSegmentedViewController.git) framework, we are glad to know that it's helping you!
We have resolved the above mentioned issue in version 1.1.2 and you can use this updated version with the following pod declaration in your podfile:

`pod 'SJSegmentedScrollView', :git => 'https://github.com/subinspathilettu/SJSegmentedViewController.git', :tag => 'v1.1.2'`
