### ISSUE TITLE
Using UIRefreshControl

### ISSUE THREAD

**Issue by esam091** [subinspathilettu/SJSegmentedViewController#29]
Hi, is there any way to use UIRefreshControl on tab items?

**Comment by SonnetXavier** [comment]
As of now, you will not be able to use UIRefreshControl on tab items.

**Comment by esam091** [comment]
alright thanks

**Comment by SonnetXavier** [comment]
Hi @esam091 ,
Just to notify you!
We have released a new version with the support to UIRefreshControl and other custom pull to refresh libs. You could use the updated version with the following pod declaration:
` pod ’SJSegmentedScrollView’, ‘1.3.5'`

**Comment by esam091** [comment]
Whoa that was quick! Thanks alot @SonnetXavier
