### ISSUE TITLE
Unable to access navigationbar

### ISSUE THREAD

**Issue by theesummer** [subinspathilettu/SJSegmentedViewController#3]
Hi,

Thanks for the module, it helped me a lot. I'm running into issue where if i try to transit to other view controller with `navigationController?.pushViewController(nextViewController(), animated: true)`, it's returning `navigationController` as `nil`. Could please let me know how can I access navigationController??

Thanks

**Comment by subinspathilettu** [comment]
Hi,

We have added content controllers as child view controllers in SJSegmentedViewController. So you need to use parent view controller to access navigation controller. 

> self.parentViewController?.navigationController!.pushViewController(viewController!, animated: true)

Thanks

**Comment by theesummer** [comment]
Thank you..!!

**Comment by aitbaali** [comment]
getting nil `navigationController`
```

if let parentViewController = self.parentViewController {
   if let navigationController = parentViewController.navigationController {
                    navigationController.pushViewController(newViewController!, animated: true)
   }
}
```

from HeaderViewController

**Comment by subinspathilettu** [comment]
@aitbaali How did you presented SJSegmentedViewController in your application? You need to use   

> public func pushViewController(viewController: UIViewController, animated: Bool) 

or

> public func addChildViewController(childController: UIViewController)

 to get navigation controller. I have updated demo application. Please check.

**Comment by aitbaali** [comment]
@subinspathilettu , thanks for the update.

I have implemented a ScrollView, and segemented controller can't scroll to top while moving scroll view to top.

**Comment by aitbaali** [comment]
@subinspathilettu any solution to my problem?

**Comment by subinspathilettu** [comment]
@aitbaali sorry, we didn't notice your issue. SegmentedController containing a scroll view. So implementing segmentedController inside a scroll view won't be work properly. Could you please share your code/project, then we have a look and provide a solution?

**Comment by aitbaali** [comment]
@subinspathilettu , my case is like [the picture](https://drive.google.com/file/d/0BxK0AQKeEdMRUWNZRHZtcktPcFE/view?usp=sharing)

**Comment by priyapy** [comment]
@aitbaali  you can use SJSegmentedViewController for your requirement were you can keep your messages, my profile segments, etc as different viewcontrollers. You don't need to use another scrollview for this. Maybe you can use a static table view to full fill your requirement. Hope this will help.

**Comment by aitbaali** [comment]
@priyapy as you say, a tableview with multiple custom cells can handle this case.
