### ISSUE TITLE
Change Unselected TitleColor

### ISSUE THREAD

**Issue by shripadkulkarid** [subinspathilettu/SJSegmentedViewController#32]
When i select title it change color.But When i select next title previous color remains same.How to change that one title color?Please Reply ASAP

**Comment by subinspathilettu** [comment]
Hi @shripadkulkarid 

Please update pod to latest version, `pod ’SJSegmentedScrollView’, ‘1.3.5'` and extend` SJSegmentedViewControllerDelegate` -> `func didMoveToPage(controller: UIViewController, segment: SJSegmentTab?, index: Int)` function.

eg:-
```Swift

var selectedSegment: SJSegmentTab?

func didMoveToPage(_ controller: UIViewController, segment: SJSegmentTab?, index: Int) {
		if selectedSegment != nil { //previous segment
			selectedSegment?.titleColor(.lightGray)
		}
		if segments.count > 0 {
			selectedSegment = segments[index]
			selectedSegment?.titleColor(.red)
		}
	}
```

**Comment by shripadkulkarid** [comment]
Thx it will help me.....
