### ISSUE TITLE
Height Issues

### ISSUE THREAD

**Issue by Karthikeyan1108** [subinspathilettu/SJSegmentedViewController#33]
setting the frame of segmentViewController like below fits the screen
 segmentedViewController.view.frame=CGRect(x:0,y:1,width:segmentedViewController.view.frame.size.width,height:segmentedViewController.view.bounds.size.height)

setting the frame to self.view.bounds pushes the view down.Please help

**Comment by SonnetXavier** [comment]
Hi @Karthikeyan1108 ,

We didn't get a clear idea of your issue, could you please specify more on your actual requirement.

**Comment by Karthikeyan1108** [comment]
I am really sorry for that.That issue was fixed.Is it possible to reduce the segment tab area based number of titles?
