### ISSUE TITLE
Tabs not showing up when upgrading from 1.3.3 to 1.3.5

### ISSUE THREAD

**Issue by yodasl** [subinspathilettu/SJSegmentedViewController#35]
I am using Pod in my project and I was previous using version 1.3.3... Earlier today I upgraded to 1.3.5 and after a "Clean" build and rebuilding the app everything compile fine and no error and no new warning... so far so good... until I run my application where the 3 tabs that should be showing up are gone!

My code is initialized:

```
        self.segmentedScrollViewController = SJSegmentedViewController(headerViewController: nil, segmentControllers: controllersForSegment)
```

and obviously my controllersForSegment object is a simple array of 3 custom subclass of UIViewController. Again no code change in my case except the upgrade to 1.3.5

After seeing that, since I was under deadline I simply reverted to 1.3.3 and everything went back to normal.

**Comment by SonnetXavier** [comment]
Hi @yodasl ,

We tried out the steps you mentioned to reproduce the issue, but we weren't able to find the issue.

**Comment by yodasl** [comment]
Hi @SonnetXavier 
Thanks for checking... I will try to see what I can find and will let you know.
