### ISSUE TITLE
How to disable Vertical scroll from ViewController.swift

### ISSUE THREAD

**Issue by minhnv85** [subinspathilettu/SJSegmentedViewController#36]
Hello,
How can we disable scroll up navigation from Viewcontroller?
We only want apply vertical scroll for child viewcontroller. Please see screenshot.
<img width="487" alt="screen shot 2017-01-11 at 1 22 17 pm" src="https://cloud.githubusercontent.com/assets/381744/21837797/0bf850e4-d801-11e6-93b1-bd817af15f0d.png">
<img width="487" alt="screen shot 2017-01-11 at 1 22 28 pm" src="https://cloud.githubusercontent.com/assets/381744/21837796/0bf5f7f4-d801-11e6-968f-8cfc49fe9205.png">

**Comment by SonnetXavier** [comment]
Sorry for the late reply, currently Vertical Scrolling cannot be disabled. We will include this feature in our next version.

**Comment by Arvaan3103** [comment]
when can release the next version? i have facing same issue. 
Thanks in advance
