### ISSUE TITLE
Container View getting pushed down if UINavigationBar + Translucent?

### ISSUE THREAD

**Issue by fabiosoft** [subinspathilettu/SJSegmentedViewController#38]
I have a UIViewController with a Container View. This Container View contains a UITableViewController.

The UIViewController is embedded in a UINavigationController. I configure the NavigationBar by changing the tint color, the bar tint color and the title text attributes, but when I try to change the translucency I have a problem

`UINavigationBar.appearance().isTranslucent = false` 

When translucent = YES

```
+---------------------------------+
|                                 |
|     UINavigationBar             |
|                                 |
+---------------------------------+
|                                 |
|                                 |
|                                 |
|                                 |
|                                 |
|    UITableViewController        |
|    in a Contained View          |
|                                 |
|                                 |
|                                 |
|                                 |
|                                 |
|                                 |
+---------------------------------+
```

when translucent = NO

```
+---------------------------------+
|                                 |
|     UINavigationBar             |
|                                 |
+---------------------------------+
|                                 |
|blank space created on top of view
|                                 |
+---------------------------------+
|                                 |
|                                 |
|                                 |
|                                 |
|                                 |
|                                 |
|     UITableViewController       |
|     in a Contained View         |
|                                 |
+---------------------------------+
```

**Comment by andrewjlow** [comment]
I have the same issue too. 

With this setting `UINavigationBar.appearance().isTranslucent = false` I get the following:

<img width="506" alt="image" src="https://cloud.githubusercontent.com/assets/5027396/23645325/ab7e5c42-035f-11e7-91f9-8435612e8160.png">

With this setting `UINavigationBar.appearance().isTranslucent = true`  I get this:

<img width="491" alt="image" src="https://cloud.githubusercontent.com/assets/5027396/23645608/1e3b78e0-0361-11e7-9310-3773b4cc025a.png">

**Comment by olivierpascal** [comment]
+1

**Comment by olivierpascal** [comment]
I think the problem is in SJUtil::getTopSpacing() that does not take in consideration isTranslucent.

**Comment by pmarrufo94** [comment]
Here is what I did to solve my problem.
For the navigation bar I added the following if statement 
` if !(navigationController?.navigationBar.isOpaque)! {
           topSpacing += (navigationController?.navigationBar.bounds.height)!
                }`
For the tab bar I modified the following if statement
`if !tabBarController.tabBar.isHidden && !tabBarController.tabBar.isOpaque {
                bottomSpacing += tabBarController.tabBar.bounds.size.height
            }`

**Comment by pratikgajbhiye222** [comment]
still m facing same issue
Help?

**Comment by sudhakar-codes** [comment]
@pratikgajbhiye222 
`if !(navigationController?.navigationBar.isTranslucent)! {
                    topSpacing -= (navigationController?.navigationBar.bounds.height)! + 3
                }else{
                    topSpacing += (navigationController?.navigationBar.bounds.height)!
                }`
