### ISSUE TITLE
Limitation

### ISSUE THREAD

**Issue by brunosilva808** [subinspathilettu/SJSegmentedViewController#4]
If i have to load this ViewController using 
`            self.presentViewController(segmentedViewController, animated: false, completion: nil)`
this is a big limitation, because for example, if i want to use it in a UITabBarViewController i wont be able to do it, because this will be presented over the TabBar.

**Comment by subinspathilettu** [comment]
Hi, Sorry for the late reply.

Did you tried by using `func pushViewController(viewController: UIViewController, animated: Bool) `?  SJSegmentedViewController is optimised for UINavigationController and UITabBarViewController. 

Still you are facing any issues, please let me know with error details.
Thanks

**Comment by subinspathilettu** [comment]
Hi @brunosilva808 ,

Hope your issue has been resolved. So I am closing this issue.
