### ISSUE TITLE
pod is not supported

### ISSUE THREAD

**Issue by sathishbliss** [subinspathilettu/SJSegmentedViewController#47]
Please find below the issues
Analyzing dependencies
Fetching podspec for `SJSegmentedScrollView` from `1.3.5`
[!] No podspec found for `SJSegmentedScrollView` in `1.3.5`

**Comment by subinspathilettu** [comment]
@sathishbliss sorry for the late reply, please update your cocoapods podspec and try

**Comment by feliciaf** [comment]
how about for swift 2.3? it is not working. how can i add it manually?

**Comment by subinspathilettu** [comment]
Sorry for the late reply, Did you tried this, https://github.com/subinspathilettu/SJSegmentedViewController#for-swift-23
