### ISSUE TITLE
broken layout when using UISplitViewController

### ISSUE THREAD

**Issue by sosuke-hirayama** [subinspathilettu/SJSegmentedViewController#5]
Hi,

Thanks for the good module.
when using UISplitViewController , layout was broken.

sample code and screen capture is here.

https://github.com/sosuke-hirayama/SJSegmentedViewControllerSample
http://d.pr/v/zVoQ

Thanks.

**Comment by subinspathilettu** [comment]
Hi @sosuke-hirayama, 

We have resolved UISplitViewController orientation change issues in latest version (1.0.12). Could you please check in your project.

**Comment by sosuke-hirayama** [comment]
@subinspathilettu 
Thank you for your immediate response. I appreciate that!
