### ISSUE TITLE
Unable to hide Refreshcontrol

### ISSUE THREAD

**Issue by ashishj-optimus** [subinspathilettu/SJSegmentedViewController#50]
Is there any way to hide the refresh control when user scrolls tableview.

![screen shot 2017-04-14 at 3 12 21 pm](https://cloud.githubusercontent.com/assets/2360223/25040073/e1210862-2124-11e7-88a2-1f70243a949f.png)

**Comment by subinspathilettu** [comment]
@ashishj-optimus You can remove refresh control from your view controller. It doesn't have a dependency with SJSegmentedControl. In the demo project, we have added refresh control in the storyboard. If you don't want to show refresh control please remove it from storyboard and check. Also, you can hide the refresh control by setting `refreshControl = nil` in your controller.
