### ISSUE TITLE
'deinit' is not calling ever. Serious Bug

### ISSUE THREAD

**Issue by JaleelNazir** [subinspathilettu/SJSegmentedViewController#56]
Controllers keeps in memory stack, not deinit. Its big issue. Please check and release new version.

**Comment by AlexGee17** [comment]
Hey! Any updates on this issue? Having same trouble here!

**Comment by AlexGee17** [comment]
Hey, @subinspathilettu ! How are you doing man? Any news on this issue? I've tested it a couple days ago and it's still in place.

**Comment by JaleelNazir** [comment]
Super, its working.
