### ISSUE TITLE
How to change start segment when viewDidLoad not using setSelectSegmentAt(_:,animated:)

### ISSUE THREAD

**Issue by 91haba** [subinspathilettu/SJSegmentedViewController#62]
When I need to change start_index of segmentController(container), 
 
 I use this code

    var start_index : Int?
    if start_index == 0{
             setSelectedSegmentAt(start_index, animated: true)
        }
        else if start_index == 1 {
            setSelectedSegmentAt(start_index, animated: true)
        }
        else if start_index == 2{
            setSelectedSegmentAt(start_index, animated: true)
        }

Above code is showing segment move animation when viewDidLoad(segmentController(container)).
But, I want to not showing movement animation when viewDidLoad(segmentController(container))

How can I do this?

**Comment by feliciaf** [comment]
did you try animated: false

**Comment by 91haba** [comment]
@feliciaf yeah, I did it. Not appear movement animation, but selected segment effect is still remain. 
I could see both selected firstTab and otherTab

**Comment by subinspathilettu** [comment]
Please use `setSelectedSegmentAt` in `viewWillAppear` func.

```
override func viewWillAppear(_ animated: Bool) {
	super.viewWillAppear(animated)
	setSelectedSegmentAt(3, animated: false)
}
```
