### ISSUE TITLE
Adding Manually problem

### ISSUE THREAD

**Issue by kemalserkan** [subinspathilettu/SJSegmentedViewController#64]
Hi 

I added SJSegmentedScrollView folder to my project 

![ekran resmi 2017-07-29 08 57 54](https://user-images.githubusercontent.com/842214/28742579-1b94afde-743c-11e7-83e4-f0cd95c496af.png)

**I had error for this line of code ;
import SJSegmentedScrollView** 
No such module 'SJSegmentedScrollView'

What can I do? I do not do anything.

**Comment by subinspathilettu** [comment]
@kemalserkan I believe you don't need import while adding the library as static.
