### ISSUE TITLE
header view not Scrolling From View Controller

### ISSUE THREAD

**Issue by pothirajp** [subinspathilettu/SJSegmentedViewController#69]
Hi Bro:

i am using SJSegmentedViewController. its good lib. easy to work.

Thank You.

Isuue is When i scroll from view controller the header view is not scrolling.
If i scroll Header view its scrolling fine.

Can u give the solution ?

**Comment by subinspathilettu** [comment]
@pothirajp I believe you need to use https://github.com/subinspathilettu/SJSegmentedViewController#customize-your-view

**Comment by takaishota** [comment]
@subinspathilettu 
It's better to change args of viewForSegmentControllerToObserveContentOffsetChange function in README.
I didn't notice this change for a while, when not work correctly

```
func viewForSegmentControllerToObserveContentOffsetChange(controller: UIViewController,
    index: Int) -> UIView {
```
->
```
func viewForSegmentControllerToObserveContentOffsetChange() -> UIView {

```

Hope this helps.

**Comment by subinspathilettu** [comment]
@takaishota Thanks for notifying me. Updated the README.
