### ISSUE TITLE
Minimal IOS version is 10 

### ISSUE THREAD

**Issue by unYannickFrechette** [subinspathilettu/SJSegmentedViewController#74]
On Xcode 9 and swift 4, I have this build error: "Module file's minimum deployment target is ios10.0 v10.0: "  

Pod installed is 1.3.8

Maybe it's normal and you just did not updated the requirements section where it is stated that the minimum ios is 9.

**Comment by subinspathilettu** [comment]
@unYannickFrechette I have updated the minimum target version to 10, (spec.ios.deployment_target  = '10.0') in latest lib update. So that you are getting this issue.

**Comment by commando24** [comment]
i have set my deployment target to 10.0 but still i am getting this error while installing pod.
