### ISSUE TITLE
i have Problem in spacing while scrolling segments or controller in left side and right side.

### ISSUE THREAD

**Issue by pradipibl** [subinspathilettu/SJSegmentedViewController#77]
![simulator screen shot - iphone 6s - 2017-11-18 at 11 55 13](https://user-images.githubusercontent.com/32387161/32977704-cc4ae3ba-cc58-11e7-852f-03fa5a688ca0.png)

**After scroll left side.**
![simulator screen shot - iphone 6s - 2017-11-18 at 13 02 19](https://user-images.githubusercontent.com/32387161/32978870-910786a6-cc70-11e7-8ec9-777556d2855e.png)

![simulator screen shot - iphone 6s - 2017-11-18 at 11 55 28](https://user-images.githubusercontent.com/32387161/32977691-83c31d38-cc58-11e7-864c-db8646c28464.png)

Also i can't set delegate method of scrollview. please give me any solution about this issue and it's very urgent.

**Comment by subinspathilettu** [comment]
@pradipibl This is not an issue. You are getting the white space while scrolling the left most and right most side as the white space is the background color.

**Comment by pradipibl** [comment]
@subinspathilettu ,
Yes you are right but how we can remove this space, We can't set this space and also have in your demo project in GitHub while you add multiple segments means more then 5-6 segment and the n you can see this issue.

**Comment by subinspathilettu** [comment]
@pradipibl I have published a new version (1.3.9) and added a property, 'segmentBounces' to set the content view bounces.

**Comment by pradipibl** [comment]
@subinspathilettu 

Thank you.. very much for fixed my issue in your product....

**Comment by subinspathilettu** [comment]
:)
