### ISSUE TITLE
How to set selected title

### ISSUE THREAD

**Issue by Mgap** [subinspathilettu/SJSegmentedViewController#8]
hy sir i am using your library its great , 
but i want ask how do change segmented title when selected

**Comment by subinspathilettu** [comment]
Hi @Mgap ,

As of now, there is no option to change selected segmented title. We will include this feature in next release.

Thanks

**Comment by Mgap** [comment]
Thanks @subinsqburst 
hope it can change font color or font feature for selected segmented title
You do great , dude

**Comment by Mgap** [comment]
Thanks @subinspathilettu ,
Hope it can change like font or title for selected segmented 
You do Great!! , dude

**Comment by subinspathilettu** [comment]
@Mgap ,

We have pushed a new version (1.1.0) of SJSegmentedScrollView to [CocoaPods](https://cocoapods.org/pods/SJSegmentedScrollView). You can access the selected segment by 

```
extension ViewController: SJSegmentedViewControllerDelegate {
    
    func didMoveToPage(controller: UIViewController, segment: UIButton?, index: Int) {
        
        if segmentedViewController.segments.count > 0 {
            
            let button = segmentedViewController.segments[index]
            button.setTitleColor(UIColor.yellowColor(), forState: .Selected)
        }
    }
}
```

You need to set the delegate to your view controller,

`segmentedViewController.delegate = self
`
