### ISSUE TITLE
RTL support has a bug 

### ISSUE THREAD

**Issue by ispha** [subinspathilettu/SJSegmentedViewController#95]
Try to use app in any language that supports Right To Left i.e Arabic , you will find such so weird behavior for the selection of tabs .like the one selected is not highlighted , it highlights the one I remove selection from , kindly try it

**Comment by ispha** [comment]
And as a fix for it I had to edit in two places in the pods which is gonna get overridden by installing any newer version so if you please take this fix in consideration for up-comming version with so much thanks in advance .Fix is so light like in attached images assuming you had a variable in user defaults tells which  current language is , i.e I have to support English(en) which is LTR and Arabic(ar) which is RTL .  Kindly let me know if any not clear , thanks again .

![screen shot 2018-03-10 at 12 33 50 am](https://user-images.githubusercontent.com/11088216/37233615-92c24c72-23fc-11e8-85d9-ccd0ee374fba.png)
![screen shot 2018-03-10 at 12 40 16 am](https://user-images.githubusercontent.com/11088216/37233616-92e909ca-23fc-11e8-9fe5-b72d4165d91a.png)

**Comment by Dev-iOS-Appbirds** [comment]
@ispha I've done provided change in my code as i've taken lib files into main target instead pod.proj but the solution is not worked for me. Can you provide anymore idea as stucked at same position.

Thanks in advance!!!
